-- ============================================================================
-- CLINICAL NOTES MIGRATION
-- ============================================================================
-- This migration updates the consultation_notes table to replace individual
-- SOAP fields (subjective, objective, assessment, plan) with a single
-- clinical_notes field that stores rich text HTML content.
--
-- IMPORTANT: This is a destructive migration. Backup your data first!
-- ============================================================================

-- Step 1: Add the new clinical_notes column
ALTER TABLE consultation_notes
ADD COLUMN IF NOT EXISTS clinical_notes TEXT;

-- Step 2: Migrate existing SOAP data to clinical_notes
-- This combines existing SOAP fields into a formatted HTML structure
UPDATE consultation_notes
SET clinical_notes =
  '<h2>Subjective</h2>' ||
  '<p>' || COALESCE(subjective, 'Not recorded') || '</p>' ||
  '<h2>Objective</h2>' ||
  '<p>' || COALESCE(objective, 'Not recorded') || '</p>' ||
  '<h2>Assessment</h2>' ||
  '<p>' || COALESCE(assessment, 'Not recorded') || '</p>' ||
  '<h2>Plan</h2>' ||
  '<p>' || COALESCE(plan, 'Not recorded') || '</p>'
WHERE clinical_notes IS NULL
  AND (subjective IS NOT NULL OR objective IS NOT NULL OR assessment IS NOT NULL OR plan IS NOT NULL);

-- Step 3: Drop old SOAP columns (OPTIONAL - only run after verifying migration)
-- UNCOMMENT the following lines after verifying that the migration was successful:

-- ALTER TABLE consultation_notes DROP COLUMN IF EXISTS subjective;
-- ALTER TABLE consultation_notes DROP COLUMN IF EXISTS objective;
-- ALTER TABLE consultation_notes DROP COLUMN IF EXISTS assessment;
-- ALTER TABLE consultation_notes DROP COLUMN IF EXISTS plan;

-- Step 4: Add constraint to ensure clinical_notes is not empty
-- UNCOMMENT after dropping old columns:

-- ALTER TABLE consultation_notes
-- ADD CONSTRAINT clinical_notes_not_empty
-- CHECK (length(trim(regexp_replace(clinical_notes, '<[^>]+>', '', 'g'))) > 0);

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run these queries to verify the migration was successful:

-- 1. Check if clinical_notes column exists and has data
-- SELECT COUNT(*) as total_consultations,
--        COUNT(clinical_notes) as with_clinical_notes,
--        COUNT(subjective) as with_soap_data
-- FROM consultation_notes;

-- 2. View a sample of migrated data
-- SELECT id,
--        LEFT(clinical_notes, 100) as clinical_notes_preview,
--        created_at
-- FROM consultation_notes
-- ORDER BY created_at DESC
-- LIMIT 5;

-- ============================================================================
-- ROLLBACK (if needed)
-- ============================================================================
-- If you need to rollback this migration before dropping old columns:

-- ALTER TABLE consultation_notes DROP COLUMN IF EXISTS clinical_notes;

-- ============================================================================
-- NOTES FOR DEVELOPERS
-- ============================================================================
-- 1. The clinical_notes field stores HTML content generated by TipTap editor
-- 2. When displaying clinical_notes, use dangerouslySetInnerHTML in React
-- 3. Consider implementing HTML sanitization for security
-- 4. Backup your database before running this migration
-- 5. Test thoroughly in a development environment first
-- ============================================================================
